### ISSUE TITLE
Addon doesn't work at all

### ISSUE THREAD

**Issue by TrueGmaner** [laytya/CustomNameplates#21]
![image](https://github.com/laytya/CustomNameplates/assets/106440850/b2b70e7e-2da9-48ff-92e9-6423fa3b8b35)
settings.lua does not affect the addon in any way. The only thing that changed after installing the addon was a black stripe, a class icon, a lvl target in the addon style
What I did:
1) Download zip
2) Move CustomNameplates folder to Interface/Addons. So path to settings.lua is C:\turttleWoW\Interface\AddOns\CustomNameplates\settings.lua
If I change every value of ["hide"] field in settings.lua to true - nothing changes. Same for ["hide"] = false. Same for changing wide, height fields - zero changes.
All other Addons (including Chronometr (thx for your job)) works fine.

**Comment by vamman311** [comment]
Having the same issue.

**Comment by laytya** [comment]
This Addon depricated 
Use Kui-Nameplates instead
