### ISSUE TITLE
How to hide chronometer without a bug?

### ISSUE THREAD

**Issue by theoden-dd** [laytya/CustomNameplates#3]
Thank you for great addon!

Just one thing that hurts comfort playing.

I confirm to use chronometer to see countdowns for enemy debuffs.
Still **I don't need an interface of chronometer** on my screen at all.
If I use "/chronometer config" and then check off "enabled" checkbox I have an error from CustomNametemplates:
> Error: ...terface\AddOns\CustomNameplates\CustomNameplates.lua:122: attempt to index field `bars' (a nil value)

As a workaround, I've set the minimal bar height, width and scale. But it's still on my screen.

Please, help me to completely get rid from it without getting the error.

Version: 1.60b-pre

**Comment by theoden-dd** [comment]
Retested in 1.70a, the error when disabling chronometer has moved a little bit, but it's still here:

> Count: Infinite
> Error: ...terface\AddOns\CustomNameplates\CustomNameplates.lua:164: attempt to index field `bars' (a nil value)

**Comment by laytya** [comment]
Just move anchor to the bottom of screen =) you will not see bars

**Comment by theoden-dd** [comment]
Eventually I came up with the same solution, thank you. =)

However it would be nice not spending performance on this visuals even outside of screen.
